"""Nginx network recovery and reconciliation.

Runs inside provision-api.  All state comes from ``user_registry.yml`` —
no separate state file needed.  The registry already records ``network_name``
for every registered user/service/label, which is the single source of truth
for reconnecting ``provision-nginx`` to user networks on startup.
"""

from __future__ import annotations

import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import docker_ops, registry

_log = logging.getLogger(__name__)


def _generated_dir() -> Path:
    """Return GENERATED_DIR from env or default."""
    return Path(
        os.environ.get("GENERATED_DIR", "/srv/provision/generated")
    )


# ---------------------------------------------------------------------------
# Stale-conf migration: v3 → v4 (QA2 — `$is_browser` regeneration path)
# ---------------------------------------------------------------------------
# v4 removed the http-level `$is_browser` Accept map from nginx.provision.conf
# (GAP-11: client type is decided by the gateway and relayed via X-Client-Type).
# Per-service confs generated by v3 still reference it, so a fresh nginx build
# crash-loops with `[emerg] unknown "is_browser" variable`. `regenerate_nginx_confs`
# re-renders every registered conf from its template (byte-identical v4 output)
# and surgically strips leftover `$is_browser` from orphan confs that have no
# registry entry.

_IS_BROWSER_IF_RE = re.compile(
    r"if\s*\(\s*\$is_browser\s*\)\s*\{.*?\}",
    flags=re.DOTALL,
)
_IS_BROWSER_TOKEN_RE = re.compile(r"\$is_browser\b")
_BLANK_LINE_RE = re.compile(r"[ \t]*\r?\n[ \t]*\r?\n")


def strip_is_browser_refs(content: str) -> str:
    """Remove v3 ``$is_browser`` scaffolding from a rendered conf.

    The v4 ``@auth_401``/``@auth_403`` named locations replaced these
    if-blocks; the browser-vs-api decision now lives in the gateway
    (``X-Client-Type``). Removing the references makes nginx parse the conf
    again (no ``[emerg] unknown "is_browser" variable``).
    """
    content = _IS_BROWSER_IF_RE.sub("", content)
    content = _IS_BROWSER_TOKEN_RE.sub("", content)
    content = _BLANK_LINE_RE.sub("\n", content)
    return content


def regenerate_nginx_confs() -> dict[str, Any]:
    """Re-render every registered per-service nginx conf with the v4 renderer.

    Migration path for stale deployed confs (v3 confs referencing the removed
    ``$is_browser`` variable). Two passes:

    1. For every registry entry with a template, re-render the conf in place
       via ``template_engine.render_nginx_conf`` — byte-identical v4
       scaffolding, no ``$is_browser``.
    2. For any conf that still references ``$is_browser`` (orphans with no
       registry entry, or entries whose re-render failed), surgically strip
       the references so nginx can parse the file again.

    Called on provision-api startup (before the nginx reload) and exposed as
    ``POST /nginx/regenerate``. Idempotent — re-rendering an already-clean conf
    is a no-op.

    Returns a dict with counts of confs regenerated / stripped + per-entry
    errors.
    """
    from . import template_engine

    generated_dir = _generated_dir()
    all_users = registry.get_all_users()
    regenerated = 0
    errors: list[dict[str, Any]] = []

    for entry in all_users:
        user_name = entry.get("user_name", "")
        service_name = entry.get("service_name", "")
        label = str(entry.get("label", "0"))
        nginx_tpl = entry.get("nginx_conf_template_path") or ""
        nginx_out = entry.get("nginx_conf_path") or ""
        if not nginx_tpl or not nginx_out:
            continue
        # domain derived from hostname = f"{service}-{user}-{label}.{domain}"
        domain = "localhost"
        hostname = entry.get("hostname", "")
        if hostname and "." in hostname:
            domain = hostname.split(".", 1)[1]
        try:
            template_engine.render_nginx_conf(
                nginx_tpl,
                nginx_out,
                user_name,
                service_name,
                label,
                domain,
                entry.get("htpasswd_path") or "",
                https=bool(entry.get("https")),
                ssl_certificate_path=entry.get("ssl_certificate_path") or "",
                ssl_certificate_key_path=entry.get("ssl_certificate_key_path") or "",
            )
            regenerated += 1
        except Exception as exc:
            errors.append({
                "user_name": user_name,
                "service_name": service_name,
                "label": label,
                "error": str(exc),
            })
            _log.warning(
                "Failed to regenerate nginx conf for %s/%s/%s: %s",
                user_name, service_name, label, exc,
            )

    # Pass 2: surgically strip $is_browser from any remaining conf (orphans).
    stripped = 0
    strip_errors: list[str] = []
    for cf in sorted(generated_dir.glob("*.nginx.conf")):
        try:
            content = cf.read_text()
            if "$is_browser" in content:
                cf.write_text(strip_is_browser_refs(content))
                stripped += 1
                _log.info("Stripped $is_browser from %s", cf.name)
        except Exception as exc:
            strip_errors.append(f"{cf.name}: {exc}")
            _log.warning("Failed to strip is_browser from %s: %s", cf.name, exc)

    return {
        "regenerated": regenerated,
        "total_registry_entries": len(all_users),
        "is_browser_stripped": stripped,
        "errors": errors,
        "strip_errors": strip_errors,
    }


# ---------------------------------------------------------------------------
# Startup recovery  (reads user_registry.yml only)
# ---------------------------------------------------------------------------


def recover_on_startup(
    nginx_container: str = "subnet-acl-nginx",
) -> dict[str, Any]:
    """Reconnect nginx to every user network listed in the registry.

    Called automatically on provision-api boot.  Idempotent — networks
    already connected are silently skipped by ``docker network connect``.

    Before touching nginx, regenerates all per-service confs from the registry
    (v3→v4 migration) so a fresh nginx build never crash-loops on stale
    ``$is_browser`` references.

    Returns
    -------
    dict with ``networks_reconnected``, ``networks_total``, ``nginx_reloaded``.
    """
    _log.info("nginx recovery: reconnecting to all user networks from registry")

    # v3→v4 stale-conf migration: write clean confs BEFORE nginx is reloaded so
    # a crash-looping nginx (stale `$is_browser`) recovers on its next restart.
    try:
        regen = regenerate_nginx_confs()
        if regen["regenerated"] or regen["is_browser_stripped"]:
            _log.info(
                "nginx recovery: regenerated %d conf(s), stripped $is_browser in %d",
                regen["regenerated"], regen["is_browser_stripped"],
            )
        if regen["errors"] or regen["strip_errors"]:
            _log.warning(
                "nginx recovery: %d conf regeneration error(s), %d strip error(s)",
                len(regen["errors"]), len(regen["strip_errors"]),
            )
    except Exception:
        _log.exception("nginx conf regeneration failed during startup recovery")

    all_users = registry.get_all_users()

    # --- Clean up zombie registry entries (written before compose_up but never started) ---
    # A zombie entry has: registry entry exists, but NO containers exist for it.
    # This happens when provision-api is killed between writing the registry and
    # calling docker compose up (e.g., during a container restart).
    # NOTE: use print() not _log.info() because the logging module may not have
    # a handler configured at startup time.
    zombies_cleaned = 0
    zombies_restarted = 0
    for entry in list(all_users):
        container_names = entry.get("container_names") or []
        compose_file = entry.get("compose_file_path", "")
        network_name = entry.get("network_name", "")
        user_name = entry.get("user_name", "")
        service_name = entry.get("service_name", "")
        label = str(entry.get("label", "0"))

        if not container_names:
            continue

        # Check if any container for this entry exists (running or stopped)
        any_exists = any(docker_ops.container_exists(c) for c in container_names)

        if not any_exists:
            # Zombie entry: registry says deployed, but no container exists.
            if compose_file and Path(compose_file).exists():
                env_file = entry.get("env_file_path") or None
                print(f"[recovery] Zombie entry {user_name}/{service_name}/{label} — starting containers via compose_up", flush=True)
                try:
                    docker_ops.compose_up(compose_file, env_file=env_file, project_name=network_name)
                    zombies_restarted += 1
                    print(f"[recovery] Zombie entry {user_name}/{service_name}/{label} — started successfully", flush=True)
                except Exception as exc:
                    print(f"[recovery] WARNING: Failed to recover zombie {user_name}/{service_name}/{label}: {exc}", flush=True)
            else:
                print(f"[recovery] Removing zombie registry entry {user_name}/{service_name}/{label} — compose file missing", flush=True)
                registry.remove_user_service(user_name, service_name, label)
                zombies_cleaned += 1

    # Reload registry after cleaning
    if zombies_cleaned or zombies_restarted:
        all_users = registry.get_all_users()

    networks = sorted({e["network_name"] for e in all_users if e.get("network_name")})

    reconnected = 0
    for net in networks:
        try:
            docker_ops.network_connect(nginx_container, net)
            reconnected += 1
        except Exception:
            _log.warning("Failed to connect %s to network %s", nginx_container, net)

    try:
        docker_ops.nginx_reload(nginx_container)
        nginx_reloaded = True
    except Exception:
        _log.warning("Failed to reload %s", nginx_container)
        nginx_reloaded = False

    _log.info(
        "nginx recovery complete: %d/%d networks reconnected, %d zombies restarted, %d zombies cleaned, nginx %s",
        reconnected, len(networks), zombies_restarted, zombies_cleaned,
        "reloaded" if nginx_reloaded else "NOT reloaded",
    )

    return {
        "networks_reconnected": reconnected,
        "networks_total": len(networks),
        "nginx_reloaded": nginx_reloaded,
        "zombies_restarted": zombies_restarted,
        "zombies_cleaned": zombies_cleaned,
    }


# ---------------------------------------------------------------------------
# Reconciliation  (live — no state file)
# ---------------------------------------------------------------------------


def run_reconciliation(
    nginx_container: str = "subnet-acl-nginx",
) -> dict[str, Any]:
    """Run a live reconciliation pass.

    Parses all ``*.nginx.conf`` files, checks whether each upstream container
    is running, reconnects nginx to every network in the registry, and reloads
    nginx.  Returns a report — nothing is persisted to disk.

    Returns
    -------
    dict with ``last_run``, ``total_upstreams``, ``reachable``,
    ``unreachable``, ``unreachable_details``, ``networks_reconnected``,
    ``nginx_reloaded``, ``upstreams``.
    """
    generated_dir = _generated_dir()
    conf_files = sorted(generated_dir.glob("*.nginx.conf"))

    upstreams: list[dict[str, Any]] = []
    reachable = 0
    unreachable = 0
    unreachable_details: list[dict[str, Any]] = []

    # --- Parse each nginx conf and verify upstream targets ---
    for cf in conf_files:
        try:
            content = cf.read_text()
            server_name = None
            proxy_pass = None

            m = re.search(r"server_name\s+([^;]+);", content)
            if m:
                server_name = m.group(1).strip().split()[0]

            m = re.search(r"proxy_pass\s+(https?://[^;]+);", content)
            if m:
                proxy_pass = m.group(1).strip()

            upstream: dict[str, Any] = {
                "conf_file": cf.name,
                "server_name": server_name,
                "proxy_pass": proxy_pass,
            }

            if proxy_pass:
                url_match = re.match(r"https?://([^:]+)(?::(\d+))?", proxy_pass)
                if url_match:
                    target_container = url_match.group(1)
                    upstream["target_container"] = target_container

                    running = docker_ops.container_running(target_container)
                    exists = docker_ops.container_exists(target_container)
                    if running:
                        upstream["reachable"] = True
                        reachable += 1
                    else:
                        upstream["reachable"] = False
                        unreachable += 1
                        reason = "container not running" if exists else "container not found"
                        upstream["reason"] = reason
                        unreachable_details.append({
                            "upstream": proxy_pass,
                            "target_container": target_container,
                            "reason": reason,
                        })
            else:
                upstream["reachable"] = None

            upstreams.append(upstream)
        except Exception as e:
            unreachable_details.append({
                "conf_file": cf.name,
                "reason": str(e),
            })
            unreachable += 1

    # --- Reconnect nginx to all networks from registry ---
    all_users = registry.get_all_users()
    networks = sorted({e["network_name"] for e in all_users if e.get("network_name")})

    networks_reconnected = 0
    for net in networks:
        try:
            docker_ops.network_connect(nginx_container, net)
            networks_reconnected += 1
        except Exception:
            pass

    # --- Check container health from stored container_names ---
    containers_healthy = 0
    containers_total = 0
    for entry in all_users:
        names = entry.get("container_names") or _derive_container_names(entry)
        for cname in names:
            containers_total += 1
            if docker_ops.container_running(cname):
                containers_healthy += 1

    # --- Reload nginx ---
    try:
        docker_ops.nginx_reload(nginx_container)
        nginx_reloaded = True
    except Exception:
        nginx_reloaded = False

    return {
        "last_run": datetime.now(timezone.utc).isoformat(),
        "total_upstreams": len(upstreams),
        "reachable": reachable,
        "unreachable": unreachable,
        "unreachable_details": unreachable_details,
        "networks_reconnected": networks_reconnected,
        "total_networks_in_registry": len(networks),
        "nginx_reloaded": nginx_reloaded,
        "upstreams": upstreams,
        "containers_healthy": containers_healthy,
        "containers_total": containers_total,
    }


def _derive_container_names(entry: dict) -> list[str]:
    """Backward-compat: derive container names from compose file if not stored."""
    compose_file = entry.get("compose_file_path", "")
    if compose_file and Path(compose_file).exists():
        try:
            import yaml
            from . import template_engine
            with open(compose_file) as f:
                data = yaml.safe_load(f) or {}
            prefix = template_engine.container_prefix(
                entry.get("service_name", ""),
                entry.get("user_name", ""),
                str(entry.get("label", "0")),
            )
            svc_keys = list(data.get("services", {}).keys())
            return [f"{prefix}{k}" for k in svc_keys]
        except Exception:
            pass
    return []


def get_nginx_state() -> dict[str, Any]:
    """Return a live snapshot of nginx state — derived from registry + Docker.

    No state file is read; everything is queried live from the registry
    and the Docker daemon.  Container health is checked for every stored
    ``container_names`` entry.
    """
    all_users = registry.get_all_users()
    networks = sorted({e["network_name"] for e in all_users if e.get("network_name")})

    # Check which networks nginx is actually connected to
    nginx_connected: list[str] = []
    for net in networks:
        if docker_ops.network_connected_to_container(net, "subnet-acl-nginx"):
            nginx_connected.append(net)

    # Per-service container health (from stored container_names in registry)
    from . import template_engine

    services: list[dict[str, Any]] = []
    for entry in all_users:
        container_names = entry.get("container_names") or _derive_container_names(entry)
        containers: list[dict[str, Any]] = []
        for cname in container_names:
            running = docker_ops.container_running(cname)
            exists = docker_ops.container_exists(cname)
            status = "running" if running else ("stopped" if exists else "missing")
            containers.append({"name": cname, "status": status})
        services.append({
            "user_name": entry.get("user_name"),
            "service_name": entry.get("service_name"),
            "label": entry.get("label"),
            "network_name": entry.get("network_name"),
            "container_names": container_names,
            "containers": containers,
        })

    # Count upstream confs
    generated_dir = _generated_dir()
    conf_files = sorted(generated_dir.glob("*.nginx.conf"))

    return {
        "total_users": len(all_users),
        "total_networks": len(networks),
        "nginx_connected_networks": len(nginx_connected),
        "networks": networks,
        "connected": nginx_connected,
        "disconnected": [n for n in networks if n not in nginx_connected],
        "total_nginx_confs": len(conf_files),
        "services": services,
    }
